version: '3.8'

services:

  db:
    image: postgres:14
    container_name: hrm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wasique@321
      POSTGRES_DB: postgres
    ports:
      - "5532:5432"   # FIXED
    volumes:
      - hrm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: hrm-backend
    restart: always
    ports:
      - "8790:8790"

    environment:
      NODE_ENV: production
      HRM_APIGATEWAY_PORT: 8790
      JWT_SECRET: ""

      # DB Writer
      PGHOST_WRITER: db
      PGPORT_WRITER: 5432
      PGUSER_WRITER: postgres
      PGPASSWORD_WRITER: wasique@321
      PGDATABASE_WRITER: postgres

      # DB Reader
      PGHOST_READER: db
      PGPORT_READER: 5432
      PGUSER_READER: postgres
      PGPASSWORD_READER: wasique@321
      PGDATABASE_READER: postgres

    depends_on:
      db:
        condition: service_healthy

volumes:
  hrm_pgdata: