version: "3.8"

services:

  db:
    image: postgres:14
    container_name: hrm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wasique@321
      POSTGRES_DB: postgres
    ports:
      - "5532:5432"
    volumes:
      - hrm_pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: hrm-backend
    restart: always
    ports:
      - "8790:8790"

    environment:
      NODE_ENV: production
      PORT: 8790

      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: wasique@321
      DB_NAME: postgres

    depends_on:
      - db

volumes:
  hrm_pgdata: